server:
  port: 8080
  servlet:
    context-path: /app

spring:
  application:
    name: messages-test-task
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username:
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  artemis:
    mode:
      EMBEDDED
    broker-url: tcp://localhost:61616
    embedded:
      enabled: true
  jms:
    template:
      default-destination: MY-QUEUE